import Image from "next/image";

export default function Home() {
  return (
    <div className="site-shell">
      <header className="site-header">
        <a className="brand" href="#top" aria-label="American Lloyd Travels home"><span className="brand-star">★</span><span className="brand-american">american</span><span className="brand-travels">Travels<br />Limited</span><span className="brand-lloyd">lloyd</span><span className="brand-plane" aria-hidden="true" /></a>
        <nav className="main-nav" aria-label="Main navigation"><a className="active" href="#top">Home</a><a href="#about">About us</a><a href="#services">Packages <span className="chevron">⌄</span></a><a href="#visa">Visa</a><a href="#contact">Contact us</a></nav>
        <button className="menu-toggle" aria-label="Open navigation">☰</button>
      </header>
      <main id="top">
        <section className="hero" aria-label="Travel destinations"><div className="hero-copy"><p className="eyebrow">Travel beyond expectations</p><h1>Make the world<br /><em>your destination.</em></h1><p className="hero-text">Curated journeys, thoughtful service, and a world of possibilities waiting for you.</p><a className="primary-button" href="#services">Explore our journeys <span>→</span></a></div><div className="hero-dots" aria-hidden="true"><span className="selected" /><span /><span /></div></section>
        <section className="intro section-wrap" id="about"><div className="intro-heading"><p className="eyebrow blue">Since 1987</p><h2>Your journey<br /><em>starts here.</em></h2></div><div className="intro-copy"><p>American Lloyd Travels Ltd is a forerunner in fully-fledged BSP ticketing, specializing in business and leisure travel with IATA accreditation.</p><p>We advocate world-class technology to create a place where people are inspired to plan and book from millions of travel options at the best price.</p><a className="text-link" href="#contact">Discover American Lloyd <span>↗</span></a></div></section>
        <section className="services-band" id="services"><div className="section-wrap"><div className="section-heading"><div><p className="eyebrow blue">Designed around you</p><h2>Our services</h2></div><p>Everything you need to go further, all in one place.</p></div><div className="service-grid">{[["01", "Airline reservations", "International ticketing made simple."], ["02", "Tailored tours", "All-inclusive journeys, made yours."], ["03", "Hotels & stays", "A comfortable welcome, anywhere."], ["04", "Car rental", "Freedom to explore at your pace."], ["05", "Visa assistance", "Friendly guidance from start to finish."], ["06", "Travel insurance", "Go confidently, wherever you go."]].map(([number, title, text]) => <article className="service-card" key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{text}</p><span className="card-arrow">↗</span></article>)}</div></div></section>
        <section className="visa-feature" id="visa"><div className="visa-image" /><div className="visa-copy"><p className="eyebrow">Travel with ease</p><h2>Visa handling,<br /><em>made easy.</em></h2><p>Getting visas done can be the most troublesome task when it comes to traveling. Our professional and friendly staff are here to help you every step of the way.</p><a className="primary-button dark-button" href="#contact">Learn more <span>→</span></a></div></section>
      </main>
      <footer className="site-footer" id="contact"><div className="footer-top section-wrap"><div><p className="eyebrow">Let&apos;s get you there</p><h2>Ready when<br /><em>you are.</em></h2></div><a className="footer-contact" href="mailto:info@americanlloydtravels.com">info@americanlloydtravels.com <span>↗</span></a></div><div className="footer-bottom section-wrap"><div className="footer-hotline"><span>HOTLINE</span><strong>+94 112 345790</strong></div><div className="socials"><a href="#contact">in</a><a href="#contact">f</a><a href="#contact">▶</a></div><p>Copyright ©2025 All Rights Reserved<br />American Lloyd Travels Ltd.</p><p><a href="#contact">IATA: 07313541</a> &nbsp;|&nbsp; Civil Aviation: A636</p></div></footer>
      <div className="cookie-notice">In order to provide you with the best online experience this website uses cookies. By using our website, you agree to our use of cookies. <a href="#contact">More Info.</a><button aria-label="Dismiss cookie notice">×</button></div>
    </div>
  );
}
